namespace ExileCore.Shared.Enums
{
    public enum ModType
    {
        None,
        Prefix,
        Suffix,
        Unique,
        Nemesis,
        Corrupted,
        BloodLines,
        Torment,
        Tempest,
        Talisman,
        Enchantment,
        EssenceMonster,
        Unknown12,
        Unknown13,
        DelveArea,
        SynthesisArea,
        SynthesisMonster,
        SynthesisMapCell,
        Unknown14,
        BlightRingAnoint,
        Unknown15,
        EnkindlingOrb,
        InstillingOrb,
        ExpeditionLogbook,
        ScourgeUpside,
        ScourgeDownside,
        ScourgeGimmick
    }
}